# Database configuration for IMI-Maps
# The default is to use SQLite; if the Postgres configuration should be
# used set the environment variable DATABASE to postgres. This is done
# in Dockerfile for the docker deployments.
# export set DATABASE=postgres

<% if ENV['DATABASE'] == "postgres" %>

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgresql
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgresql
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>-test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgresql
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>


<% else
  puts "WARNING: ENV['DATABASE'] not set to \"postgres\", using default: SQLITE"
%>

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

<% end %>
