
<% if ENV['POSTGRES_USER'] %>

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgresql
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgresql
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>-test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgresql
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
<% else
  puts "WARNING: ENV['POSTGRES_USER'] not set, using SQLITE DB Configuration"
  %>

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

<% end %>
